Add MermaidJS plugin
kakawait/hugo-tranquilpeak-theme pull request #513
Opened 2021-09-07 09:09 UTC by AnceretMatthieu

This pull request add MermaidJS shortcode to this theme (you can see a example here : https://anceret-matthieu.fr/2020/09/mermaid/).
Mermaid allow to draw diagram and schema with text (Markdown syntax like).

If you have questions or feedback I'm happy to discuss.

Matthieu.

2021-09-07 09:42 UTC, kakawait commented
Thank you

Attention you've downgraded some other 3rd party libs

2021-09-10 17:14 UTC, kakawait requested changes

2021-09-10 17:14 UTC, kakawait commented on layouts/partials/script.html
> +  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js" crossorigin="anonymous"></script>
Can we use this instead 

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.12.1/mermaid.min.js" integrity="sha512-08D1plquyGkiMn9uWbY5ZgCrfpZo5hZ6Ab89VPOCZ8zGkPU428uaUDAAqYjCMrbz2ECFG/VR8v470aY9CiB1HA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
```

Isn't jsdelivr the problem but:

1. I still prefer fixed version
2. I've plan to support configurable CDN to do not force user to use cloudflare DNS. It will be easier for me, if for the moment we keep consistency. Will be simpler to migrate after

2021-09-10 17:14 UTC, kakawait commented on layouts/partials/script.html
> +  <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.8.3/prism.min.js" integrity="sha256-haEv2ilTk2sXcJaGbkTtErRCHy/qGt3g+bGbgPf5OTY=" crossorigin="anonymous"></script>
Please rollback to `1.24.1`

2021-09-10 17:14 UTC, kakawait commented on layouts/partials/script.html
> +<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.7/js/jquery.fancybox.min.js" integrity="sha256-GEAnjcTqVP+vBp3SSc8bEDQqvWAZMiHyUSIorrWwH50=" crossorigin="anonymous"></script>
Please remove, fancybox already present next line 

https://github.com/kakawait/hugo-tranquilpeak-theme/pull/513/files#diff-104dce89080d1f79bc4644eee46fb18a66c8e277ee30c5de66c23c310271939fR15

2021-09-14 07:41 UTC, AnceretMatthieu commented on layouts/partials/script.html
> +<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.7/js/jquery.fancybox.min.js" integrity="sha256-GEAnjcTqVP+vBp3SSc8bEDQqvWAZMiHyUSIorrWwH50=" crossorigin="anonymous"></script>
Sorry i missed that...

2021-09-14 07:44 UTC, AnceretMatthieu commented on layouts/partials/script.html
> +  <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.8.3/prism.min.js" integrity="sha256-haEv2ilTk2sXcJaGbkTtErRCHy/qGt3g+bGbgPf5OTY=" crossorigin="anonymous"></script>
Why ? Is this a compatibility issue ?

2021-09-14 10:08 UTC, kakawait commented on layouts/partials/script.html
> +  <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.8.3/prism.min.js" integrity="sha256-haEv2ilTk2sXcJaGbkTtErRCHy/qGt3g+bGbgPf5OTY=" crossorigin="anonymous"></script>
No because current version is the lastest which is 1.24.x and with your PR you've downgraded to 1.8.x

2021-09-25 11:01 UTC, kakawait commented
Perfect. I'll merge.

However I was thinking on something that will automatically load JS dependency as soon you use mermaid on the page. To avoid explicitly use mermaid param.

So maybe on coming commit I'll remove that param

2021-09-25 11:02 UTC, merged